### ISSUE TITLE
Cannot be installed on Eclipse IDE prior to Mars 1.0

### ISSUE THREAD

**Issue by vlatko019** [echebbi/eclipse-discord-integration#35]
Got this error and the message that apears in details is: 
"Missing requirement: Discord Rich Presence 0.8.3 (fr.kazejiyu.discord.rpc.integration.feature.feature.group 0.8.3) requires 'org.eclipse.ui.workbench"

Any idea what should I do? I have org.eclipse.ui.workbench installed... 

![capture](https://user-images.githubusercontent.com/7595584/41128203-a5919acc-6aad-11e8-9030-b84304bbb258.PNG)

![capture1](https://user-images.githubusercontent.com/7595584/41128296-f34e94d6-6aad-11e8-84d9-2feee80d28ee.PNG)

**Comment by vlatko019** [comment]
It is Luna. I'll download OXYGEN then and try again.

Thank you!

**Comment by echebbi** [comment]
Luna is almost 5 year old. I will assume that supporting Mars will be enough for the majority of developers.
