### ISSUE TITLE
Display library class

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [echebbi/eclipse-discord-integration#84]
## Motivation

I think it would be cool if there was an option we could enable, that showed the class we are viewing even if its a library/dependency. Maybe instead of editing x.java it could be viewing x.java.

**Comment by echebbi** [comment]
Shouldn't be too long to implement, I'll push a fix soon.

**Comment by echebbi** [comment]
The new `1.2.2` release should handle _.class_ files; can you test and confirm that it matches your needs?

**Comment by THEREALWWEFAN231** [comment]
Just tested it, yes it does, thank you, very cool!

**Comment by echebbi** [comment]
You're welcome!
