### ISSUE TITLE
Not working on lasted Eclipse version

### ISSUE THREAD

**Issue by Laval13** [echebbi/eclipse-discord-integration#87]
Hey, I'm in the latest version of Eclipse, I downloaded the plugin but I don't have the plugin settings in "Preferences" and the Rich Presence doesn't display on Discord

- **Plug-in version**: 1.2.2
- **Eclipse IDE version**: Eclipse IDE for Java Developers - 2020-06

**Comment by echebbi** [comment]
Hey there so, uuuh, it's been one year already. I'm deeply sorry, I completely missed your issue. I just tried to install the plug-in on 2020-06 and it works as expected. I'm closing the issue but feel free to re-open it or to fill a new issue if you still face the problem.
