### ISSUE TITLE
Extension Can't Be Installed (Forbidden)

### ISSUE THREAD

**Issue by Cullen36** [echebbi/eclipse-discord-integration#92]
## Bug description

This plugin is currently impossible to install with Eclipse both via Marketplace and P2.
The reason for this is because the URL "https://dl.bintray.com/kazejiyu/eclipse-discord-integration/" returns "Forbidden!" when visited and therefore Eclipse cannot access the necessary files.

## Expected behavior

Installing the plugin via Marketplace or P2 works correctly

## Resulting behavior
An error occurs because the files cannot be accessed.

## How to reproduce

1. Go to Eclipse Marketplace or "Install new software."
2. Find the plugin and follow typical installation procedure.
4. Witness the error. Manually visiting the URL also shows the error.

## Additional context
This should be easy to fix I assume since it seems to just be an issue with access settings on bintray.

- **Plugin Version: Latest (1.2.2)**
- **Eclipse Release: 4.19**

**Comment by echebbi** [comment]
> This should be easy to fix I assume since it seems to just be an issue with access settings on bintray.

Actually Bintray has shutdown its services so I have to deploy the plug-in to another place: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I'm terribly sorry for the inconvenience, I'll do my best to provide a solution by the end of the week.

**Comment by Candy-Sama** [comment]
Hi there! I just wanted to tag onto this without being too much of a bother ;~;

Is there any updates? :O

**Comment by echebbi** [comment]
> Is there any updates? :O

Yes, there is! :) I actually deployed the latest version just a few minutes ago; the Eclipse Marketplace has been updated so you should be able to install it now.

For those who may be interested in the direct p2 link, the repository is now on GitHub:
 - https://echebbi.github.io/eclipse-discord-integration-updates/releases/1.2.2

To use it:

1. Open Eclipse IDE
2. Go to _Help > Install New Software..._
3. Copy the update site’s URL in the _Work with_ textbox:
   - https://echebbi.github.io/eclipse-discord-integration-updates/releases/1.2.2
4. Hit _Enter_ and wait for the list to load
5. Check _Discord Rich Presence for Eclipse IDE_
6. Click _Next_ then _Finish_

I apologize again for the inconvenience and I thank you for waiting.

**Comment by Candy-Sama** [comment]
Thank you very much!!
